Add the ability to use a Tile ControlNet for iterative tiled upscaling
ltdrdata/ComfyUI-Impact-Pack pull request #404
Opened 2023-12-28 20:31 UTC by narukaze132

I frequently use the Tile ControlNet when I am using tiled upscaling, because from my experience it makes the results much more cohesive than standard tiling without having to use an incredibly vague prompt. I find that I get the best results from using each upscaled image for the ControlNet, which means it needs to be used partway through the IterativeLatentUpscale process for the best results. As such, I decided to add support for easily using the Tile ControlNet in the TiledKSample upscaling process provided by this repo. (This functionality will require comfy-controlnet-aux to be installed in order to work correctly.)

I apologize for submitting this while my other pull request is still under review, but I also intend to work on implementing the SD-Latent-Upscaler functionality for upscaling eventually, and since it involves almost the exact same areas of code, I'd prefer to have this pull request confirmed or denied before I begin work on that (to ease later merging). I am considering allowing the pyrUp_iters of the Tile Preprocessor to be manipulated by the user, though, so I'm going to submit this as a draft for now.

2023-12-29 05:39 UTC, ltdrdata commented
It is recommended to use https://github.com/Ttl/ComfyUi_NNLatentUpscale as the upscaler in the latent space. NNLatentUpscaler allows for more flexible adjustment of the upscale size and does not produce the stripe pattern observed in SD-Latent-Upscaler.

2023-12-29 21:08 UTC, narukaze132 commented
@ltdrdata Understood, I'll keep that in mind when working on that functionality.

On the matter of this pull request, I attempted to add the ability to modify the pyrUp_iters parameter (for the preprocessor), but couldn't get it to work correctly on the JavaScript side of things. As such, I'm simply going to leave it with a reasonable hardcoded value, and open the commit for review. (I may revisit this later on.)

2023-12-30 12:26 UTC, ltdrdata commented
This workflow is failing...

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/extreme-highscale.png

```
Traceback (most recent call last):
  File "/mnt/teratera/git/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1078, in doit
    current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI-Impact-Pack/modules/impact/core.py", line 1604, in upscale_shape
    refined_latent = nodes.KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/nodes.py", line 1256, in common_ksampler
    latent_image = latent["samples"]
                   ~~~~~~^^^^^^^^^^^
TypeError: tuple indices must be integers or slices, not str


```

2023-12-30 14:28 UTC, narukaze132 commented
Ah, I think I accidentally broke other upscaling providers. I'll fix it
later today.

On Sat, Dec 30, 2023, 7:27 AM Dr.Lt.Data ***@***.***> wrote:

> This workflow is failing...
>
>
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/extreme-highscale.png
>
> Traceback (most recent call last):
>   File "/mnt/teratera/git/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1078, in doit
>     current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI-Impact-Pack/modules/impact/core.py", line 1604, in upscale_shape
>     refined_latent = nodes.KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler,
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI/nodes.py", line 1299, in sample
>     return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/teratera/git/ComfyUI/nodes.py", line 1256, in common_ksampler
>     latent_image = latent["samples"]
>                    ~~~~~~^^^^^^^^^^^
> TypeError: tuple indices must be integers or slices, not str
>
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/404#issuecomment-1872518743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYNGPJ7AKDR2KD2ZFNPY63YMACBVAVCNFSM6AAAAABBF4AAG2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSGUYTQNZUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-31 18:56 UTC, narukaze132 commented
Alright, it should be fixed now. Sorry about the delay. (I didn't actually check it because my computer can't handle that workflow, though.)

2024-04-25 12:53 UTC, ltdrdata requested changes

2024-04-25 12:53 UTC, ltdrdata commented on modules/impact/core.py
> +                preprocced = preprocessor.execute(images, pyrUp_iters=3, resolution=min(image_w, image_h))
I think you forgot to pass the `preprocessed` image to `apply_cnet`.

2024-04-25 12:55 UTC, ltdrdata commented on modules/impact/core.py
> +                preprocced = preprocessor.execute(images, pyrUp_iters=3, resolution=min(image_w, image_h))
The review was pending due to my mistake.

2024-04-25 16:09 UTC, narukaze132 commented on modules/impact/core.py
> +                preprocced = preprocessor.execute(images, pyrUp_iters=3, resolution=min(image_w, image_h))
D'oh, you're right. Fixed.

2024-04-26 16:12 UTC, ltdrdata approved these changes

2024-04-26 16:13 UTC, merged