node to create wildcard label prompt from string list
ltdrdata/ComfyUI-Impact-Pack pull request #536
Opened 2024-04-01 21:03 UTC by jkrauss82

The idea behind this node is to automatically create a wildcard prompt for the SEGS detailer. The purpose is to have a single prompt per tile/SEG which guides a denoising process for upscaling an image (in addition to the regular upscale prompt).

This strategy should help to either increase the denoising strength for added details or protect against hallucinations at the same denoise level.

The [WD14 tagger of pythongosssss](https://github.com/pythongosssss/ComfyUI-WD14-Tagger) works nicely for assigning tags on the fly for each tile. It is required to use that or something else to create the string list for the node input.

A prototype workflow is attached to this PR.

[prompt-per-tile-sample.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14828491/prompt-per-tile-sample.json)

2024-04-25 12:51 UTC, ltdrdata requested changes

2024-04-25 12:51 UTC, ltdrdata commented on modules/impact/util_nodes.py
> +        if prefix_all[0] == None: prefix_all[0] = ""
In Python, when checking if something is None, you should use `is None`.

2024-04-25 12:51 UTC, ltdrdata commented on modules/impact/util_nodes.py
> +    INPUT_IS_LIST = True
The behavior seems unclear because `string_list` is received as a list while the others are not being considered as lists.

It might be better to add a node such as `StringListToString` instead of directly receiving `string_list` in this node, and receive input as a concatenated `string`.

2024-04-25 12:54 UTC, ltdrdata commented on modules/impact/util_nodes.py
> +    INPUT_IS_LIST = True
The review was pending due to my mistake.

2024-05-01 08:01 UTC, jkrauss82 commented on modules/impact/util_nodes.py
> +        if prefix_all[0] == None: prefix_all[0] = ""
Resolved by https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/536/commits/43e1bbbef3fa0000fdcda9a4959b76771f207719

2024-05-01 09:28 UTC, jkrauss82 commented on modules/impact/util_nodes.py
> +    INPUT_IS_LIST = True
That makes sense.

I have added this node here: https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/536/commits/e41788aafa0a14eaeb70bb7dfce99be17cc0d027 (used [WAS node suite](https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/WAS_Node_Suite.py#L9588) `WAS_Text_List_to_Text` as template).

A new workflow making use of the added node is attached.

[prompt-per-tile-sample.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/15175841/prompt-per-tile-sample.json)

2024-05-01 10:05 UTC, ltdrdata approved these changes

2024-05-01 10:05 UTC, merged

2024-05-04 17:56 UTC, gonzalu commented on modules/impact/util_nodes.py
> +    INPUT_IS_LIST = True
That's awesome

2024-06-15 13:33 UTC, jkrauss82 commented on modules/impact/util_nodes.py
> +    INPUT_IS_LIST = True
> That's awesome

thanks!

I have finally found the time to write up a short tutorial in the impact examples on how I imagine this node to be used, check it out [here](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/PromptPerTileUpscale.md)